name: employeemonitor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'  # More precise SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.1
  uuid: ^4.5.1
  intl: ^0.20.2
  provider: ^6.1.5
  permission_handler: ^12.0.0
  qr_code_scanner: ^1.0.1
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.9.1
  flutter_animate: ^4.5.2
  image_picker: ^1.1.2
  # Removed flutter_config as it's redundant with flutter_dotenv

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env